If no bug tracker is selected, even though the "Link to external bug"
checkbox is checked, we get an error message.

    >>> browser.addHeader('Authorization', 'Basic test@canonical.com:test')
    >>> browser.open(
    ...     'http://localhost/distros/debian/+source/mozilla-firefox/+bug/3')
    >>> browser.getLink('Upstream').click()

    >>> browser.getControl('Product').value = 'thunderbird'
    >>> browser.getControl(name='field.link_to_bugwatch').value = True
    >>> browser.getControl('Remote Bug Tracker').value = []
    >>> browser.getControl(name='field.remotebug').value = '12'
    >>> browser.getControl('Continue').click()

    >>> print browser.contents
    <!...There is 1 error...
    ...Please specify a bug tracker...

