POSubmissionSet
===============

This class represents the set of POSubmission objects in our database.
We use it to get a concrete submission when we know its ID.

Let's do some imports we will need to test this class.

  >>> from zope.component import getUtility
  >>> from canonical.launchpad.interfaces import IPOSubmissionSet
  >>> posubmissionset = getUtility(IPOSubmissionSet)

getPOSubmissionByID
-------------------

With this method, we can get the POSubmission object that has the given
id as argument or None when it doesn't exist.

We can get a POSubmission object that exists.

  >>> posubmission = posubmissionset.getPOSubmissionByID(1)
  >>> posubmission is None
  False
  >>> posubmission.id
  1

And we get None when there isn't any POSubmission with the given ID.

  >>> posubmission = posubmissionset.getPOSubmissionByID(100000)
  >>> posubmission is None
  True


POSubmission
============

This class links the translations submitted by a translator with the associated.

destroySelf
-----------

With this method, we allow to remove a submission, it comes from SQLObject,
but we test it here to be sure it appears in our public interfaces.

We will need extra permissions to use this method.

    >>> import transaction
    >>> from canonical.launchpad.ftests.harness import LaunchpadFunctionalTestSetup
    >>> LaunchpadFunctionalTestSetup(dbuser='rosettaadmin').setUp()

It needs that there are no references to it to be able to remove it.

    >>> from canonical.launchpad.database import POSubmission
    >>> posubmission = POSubmission.get(1)

XXX CarlosPerelloMarin 20060426: We need to use try/except here because
Dapper (my laptop) raises an IntegrityError but Breezy (pqm) raises
ProgrammingError. We use DatabaseError because it's a superclass of both and 
should be available on both systems.

    >>> from psycopg import DatabaseError
    >>> try:
    ...     posubmission.destroySelf()
    ... except DatabaseError:
    ...     print 'We were not able to remove this posubmission'
    We were not able to remove this posubmission

Restore the database access after the failure.

    >>> transaction.abort()

Let's retry with a submission that we know is not referenced.

    >>> posubmission = POSubmission.get(693)
    >>> posubmission.destroySelf()

It should not exist now.

    >>> posubmission = POSubmission.get(693)
    Traceback (most recent call last):
    ...
    SQLObjectNotFound:...

    >>> LaunchpadFunctionalTestSetup().tearDown()
